### ISSUE TITLE
Removing namespace block

### ISSUE THREAD

**Issue by peter279k** [jason-napolitano/PHP-Exceptions#9]
According to the official [PHP doc](https://www.php.net/manual/en/language.namespaces.definitionmultiple.php), the namespace is doc only for multiple namespaces in same PHP file.

I think these blocks should be removed because there're no PHP files with multiple namespaces in `tests` and `src` directories.

**Comment by jason-napolitano** [comment]
I only do this as a personal preference since I like the indentations of a class wrapped in a namespace block. Since it is not a functionality concern we can leave it for now. I may just add a rule in my custom code beautifier that removes this before committing. For now, it's okay to remain.

Thanks!

**Comment by jason-napolitano** [comment]
On my mobile I accidentally closed this =P.

**Comment by peter279k** [comment]
Closed this via PR #11.
